title: CFD Streamline
email: cfd.streamline@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  CFD Streamline is a comprehensive reference for Computational Fluid Dynamics (CFD) and its application accross the engineering areas, mainly focusing on aerospace and automotive.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cfdstreamline
github_username: cfdstreamline

theme: jekyll-theme-minimal
